# Generated by Django 4.1.6 on 2023-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminCd', models.CharField(max_length=15)),
                ('longTermAdminNm', models.CharField(max_length=100)),
                ('adminPttnName', models.CharField(max_length=20)),
                ('ratingCd', models.CharField(max_length=15)),
                ('siDoName', models.CharField(max_length=20)),
                ('siGunGuName', models.CharField(max_length=20)),
                ('ratingDate', models.DateField()),
                ('ratingGrade', models.CharField(max_length=1)),
                ('opRating', models.IntegerField()),
                ('safeRating', models.IntegerField()),
                ('rightRating', models.IntegerField()),
                ('processRating', models.IntegerField()),
                ('resultRating', models.IntegerField()),
            ],
        ),
    ]
