# Generated by Django 4.1.6 on 2023-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_alter_carerank_oprating_alter_carerank_processrating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionCd', models.IntegerField(blank=True, null=True)),
                ('regionNm', models.CharField(blank=True, max_length=200, null=True)),
                ('siDoNm', models.CharField(blank=True, max_length=10, null=True)),
                ('siGunGuNm', models.CharField(blank=True, max_length=10, null=True)),
                ('umdNm', models.CharField(blank=True, max_length=10, null=True)),
                ('riNm', models.CharField(blank=True, max_length=10, null=True)),
                ('siDoCd', models.IntegerField(blank=True, null=True)),
                ('siGunGuCd', models.IntegerField(blank=True, null=True)),
                ('DongCd', models.IntegerField(blank=True, null=True)),
                ('riCd', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
