# Generated by Django 4.1.6 on 2023-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerank',
            name='opRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='processRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='ratingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='ratingGrade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='resultRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='rightRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='safeRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='siDoName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carerank',
            name='siGunGuName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
